import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../../components/navbar";
import Card from "../../components/propertyCard";
import { HeroSection } from "../../components/heroSection";
import { SearchProperty } from "../../components/searchProperty";
import PropertyCard from "../../components/propertyCard";
import AddPropertyForSell from "../../components/addProperty";
import PropertyDetails from "../../components/propertyDetails";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navbar />
      <HeroSection />
      <PropertyCard />
      <AddPropertyForSell />
      <PropertyDetails />
      {/* <SearchProperty /> */}
    </>
  );
}
